import { Translations, Review } from './types';

export const WEBHOOK_URL = 'https://n8n.queensautoservices.com/webhook/5d232542-49e5-46ac-a638-3967b7acdfc9';

export const translations: Translations = {
    en: {
        readLess: "Read less",
        readMore: "Read more",
        navClaimOffer: "Claim Offer",
        heroClaimOffer: "Claim Alignment Offer Now!",
        bookNow: "Book Now",
        limitedSlots: "Professional Wheel Alignment",
        heroTitle: "<span class=\"text-transparent bg-clip-text bg-gradient-to-r from-cyan-400 to-blue-500\">Perfect Precision:</span> Get $35 OFF Wheel <span class=\"text-highlight\">Alignment</span> (per axle)",
        heroSubtitle: "Protect your tires and improve your fuel economy with a precision wheel alignment. Ensure your vehicle drives straight, stays safe, and handles perfectly. Claim your $35 OFF coupon today and get a free suspension inspection to keep you moving smoothly.",
        bulletAlignmentService: "Get $35 OFF Professional Wheel Alignment (per axle)",
        bulletBonus1: "<strong>Bonus 1:</strong> FREE Suspension Inspection ($59 Value)",
        bulletBonus2: "<strong>Bonus 2:</strong> FREE Tire Pressure Check & Adjustment",
        bulletBonus3: "<strong>Bonus 3:</strong> FREE Steering Component Check",
        bulletBonus4: "<strong>Bonus 4:</strong> 15% OFF Any Necessary Suspension Repairs",
        heroCTA: "Claim My $35 OFF Alignment (per axle) →",
        trustedBy: "<span class=\"text-amber-400\">★★★★★</span> 4.9 from 250+ Algonquin drivers",
        scarcityLine: "⏰ Only 5 alignment slots left this week",
        restrictionsApply: "Restrictions Apply.",
        seeDetails: "See Details",
        disclaimerTitle: "Offer Details",
        disclaimerBody: "$35 OFF special applies to wheel alignment per axle for most passenger cars and light trucks. Offer includes toe adjustments where applicable. Camber and caster adjustments may incur additional labor charges. Excludes vehicles with modified suspensions, luxury/performance models requiring specialized equipment, and heavy-duty trucks over 1 ton. Cannot be combined with other offers. See store for full details.",
        formTitle: "Secure Your Spot - Get Started Here",
        formStep1: "Step 1 of 2 — Your contact details.",
        formStep2: "Step 2 of 2 — Pick your preferred time.",
        formStep3: "", // Unused
        symptomSqueaking: "Vehicle pulls to one side",
        symptomSpongy: "Uneven or rapid tire wear",
        symptomShaking: "Steering wheel is crooked",
        symptomLight: "Steering wheel vibrates",
        symptomCheck: "Just need a routine alignment check",
        nextBtn1: "Next → Lock In My Discount",
        firstName: "First Name",
        lastName: "Last Name",
        email: "Email",
        mobileNumber: "Mobile Number",
        vehicleDetails: "Vehicle Details",
        carYear: "Year",
        carMake: "Make",
        carModel: "Model",
        backBtn: "Back",
        nextBtn2: "Next → Pick a Time",
        availableTimes: "Available Times",
        submitBtn: "Secure My Spot →",
        noPaymentRequired: "No payment required — this just saves your spot.",
        requiredField: "This field is required",
        whenToReplaceTitle: "When to Get Your Wheels Aligned",
        whenToReplaceSubtitle: "Poor alignment can damage your tires and compromise your safety. Watch for these common warning signs.",
        watchSignsTitle: "Watch for These Signs",
        signSqueakingTitle: "Vehicle pulling to one side",
        signSqueakingBody: "If your car drifts left or right when you have a straight grip on the steering wheel, your alignment is likely off.",
        signSpongyTitle: "Uneven tire wear",
        signSpongyBody: "Check your tread. If one side is wearing faster than the other, your wheels aren't properly aligned.",
        signStoppingTitle: "Steering wheel vibration",
        signStoppingBody: "A vibrating steering wheel can be a sign of poor alignment or unbalanced tires.",
        signLightTitle: "Crooked steering wheel",
        signLightBody: "If your steering wheel is off-center while driving straight, it's time for a professional alignment.",
        dontWaitTitle: "Don’t Wait—Protect Your Tires",
        dontWaitBody: "Delaying an alignment risks ruining a set of expensive tires in just a few thousand miles.",
        dontWaitCTA: "Claim $35 OFF Alignment (per axle) →",
        alignmentsPerformed: "1,000s of Alignments Performed",
        expertRepairTitle: "Precision Wheel Alignment, Done with Care.",
        expertRepairIntro: "At our shop in Algonquin, we use state-of-the-art laser alignment technology to ensure your vehicle meets factory specifications. Proper alignment is key to tire longevity and road safety. Here's what's included in our process:",
        bulletEquipment: "State-of-the-Art Laser Alignment",
        bulletInspection: "Free Suspension Inspection Included",
        bulletWarranty2: "<strong>Precision Guaranteed to Factory Specs</strong>",
        bulletFinancing: "Financing Available Through Snap",
        bulletVehicles: "Valid on Most Passenger Vehicles",
        trustedByDrivers: "Trusted by drivers across Algonquin, Lake in the Hills, and beyond.",
        feature1Title: "State-of-the-Art Laser Tech",
        feature1Body: "We use high-precision Hunter Hawkeye laser systems to measure your wheel angles to within a fraction of a degree, ensuring a perfect straight-line drive.",
        feature2Title: "Comprehensive Suspension Check",
        feature2Body: "Before aligning, we inspect ball joints, tie rods, and bushings. We won't align a car with worn parts that won't hold the settings.",
        feature3Title: "Digital Before & After Reports",
        feature3Body: "Transparency is everything. You'll receive a detailed printout showing your vehicle's alignment before and after our adjustments.",
        feature4Title: "Expert Road Test",
        feature4Body: "Every alignment is followed by a road test to confirm the steering wheel is perfectly centered and the vehicle handles exactly as it should.",
        whyImportantTitle: "Why You Shouldn't Ignore Poor Alignment",
        whyImportantSubtitle: "Misalignment isn't just a nuisance—it's expensive and unsafe.",
        pain1Title: "Rapid Tire Destruction",
        pain1Body: "Misaligned wheels can scrub the tread off your tires in just a few thousand miles, costing you hundreds in premature replacements.",
        pain2Title: "Poor Fuel Economy",
        pain2Body: "When your wheels aren't pointing straight, your engine works harder to push the car, burning more gas every mile.",
        pain3Title: "Unsafe Handling",
        pain3Body: "Misalignment affects your ability to steer accurately, especially in emergency situations or on wet roads.",
        reliefStatement: "🔒 Guaranteed Precision — We ensure your vehicle drives straight and true, or we'll make it right.",
        bookServiceCTA2: "Claim $35 OFF Alignment (per axle) →",
        trustRating: "4.9 Google Rating",
        trustRatingSub: "From 250+ happy customers",
        trustExp: "10,000+ Alignments",
        trustExpSub: "Completed in Algonquin since 2007",
        trustWarranty: "Precision Guaranteed",
        trustWarrantySub: "Peace of mind guaranteed",
        promiseTitle: "Our Precision Alignment Guarantee",
        promiseSubtitle: "Every alignment we perform is backed by our commitment to precision, honesty, and your absolute satisfaction. Every service is backed by these four commitments.",
        promise1Title: "Upfront Pricing",
        promise1Body: "The price we quote is the price you pay. No surprises, no hidden fees. Just honest work at a fair price.",
        promise2Title: "Modern Technology",
        promise2Body: "We use the latest Hunter Hawkeye laser alignment systems for unmatched precision and accuracy.",
        promise3Title: "Expert Technicians",
        promise3Body: "Our experienced technicians are alignment specialists, ensuring your service is done right the first time.",
        promise4Title: "Satisfaction Guarantee",
        promise4Body: "If you're not happy with how your car drives after our alignment, bring it back and we'll re-check it for free.",
        testimonialsTitle: "Trusted by <span class=\"text-cyan-400\">Algonquin Drivers</span>",
        testimonialsSubtitle: "Algonquin drivers count on Queens Auto for fast, affordable, and reliable wheel alignments. See why 25,000+ customers won’t go anywhere else.",
        loadMore: "Load More Reviews",
        aboutTitle: "Algonquin’s Trusted Neighborhood Auto Repair Shop",
        aboutBody: "Queens Auto Service is proud to serve the Algonquin community with reliable, honest car care. As a family-owned shop, we treat every customer like a neighbor and every vehicle like our own. Whether you're here for a precision alignment, routine maintenance, or unexpected repairs — we’ve got your back with fair prices and real solutions.",
        aboutPoint1: "Honest & Transparent Pricing",
        aboutPoint2: "Experienced, Professional Technicians",
        aboutPoint3: "24-Month / 24,000-Mile Warranty on Most Repairs",
        aboutPoint4: "Over 25,000 cars fixed and counting.",
        aboutSubtext: "For over 17 years, we’ve served Elgin, Carpentersville, Dundee, Algonquin, and nearby communities. We’re a family-owned shop you can trust.",
        parallaxTitle: "Car Pulling? Don't Let It Ruin Your Tires!",
        parallaxBody: "Misalignment is the #1 cause of premature tire wear. Our laser-precision technology gets you back on the straight and narrow. Save $35 on your alignment (per axle) today and protect your tires.",
        parallaxCTA: "Claim My $35 OFF Alignment (per axle) →",
        serviceAreaTitle: "Proudly Serving Algonquin & the Surrounding Communities",
        faqTitle: "Queens Auto Wheel Alignment FAQ",
        faqSubtitle: "Everything you need to know about our alignment services — answered clearly and simply.",
        faq1q: "How often should I get an alignment?",
        faq1a: "We recommend checking your alignment every 6,000 miles or whenever you get new tires. If you hit a large pothole or notice your car pulling, you should get it checked immediately to avoid tire damage.",
        faq2q: "How long does a wheel alignment take?",
        faq2a: "Most alignments at Queens Auto are completed in about 45 to 60 minutes. We'll provide you with a detailed report showing the adjustments we made to bring your car back to factory specs.",
        faq3q: "How much does a wheel alignment cost?",
        faq3a: "Get $35 OFF our standard precision wheel alignment per axle. Regular prices vary by vehicle type, but most passenger vehicles see significant savings with this offer. This includes adjustments to toe settings.",
        faq4q: "Do you offer a warranty on alignment work?",
        faq4a: "We guarantee our alignment work. If you notice any issues with your steering or handling within 30 days of service, bring it back and we'll re-check and adjust it for free.",
        faq5q: "Can I drive with bad alignment?",
        faq5a: "Technically yes, but it's not safe or cost-effective. Bad alignment makes your car harder to control and destroys tires rapidly. It's much cheaper to get an alignment than to buy a new set of tires.",
        faq6q: "What vehicles do you align?",
        faq6a: "We work on most cars, SUVs, and light trucks — foreign or domestic. Our equipment is compatible with almost all modern vehicle makes and models.",
        faq7q: "What if my suspension is worn?",
        faq7a: "No problem. We perform a free suspension check before every alignment. If we find worn parts (like tie rods or ball joints) that would prevent a proper alignment, we'll let you know first.",
        faq8q: "Does alignment include tire balancing?",
        faq8a: "No, alignment and balancing are separate services. Alignment adjusts the angles of the wheels, while balancing ensures the weight is even around the tire and wheel assembly. We can do both if needed!",
        faq9q: "How do I know if I need an alignment?",
        faq9a: "If your steering wheel is crooked, the car pulls to one side, or you see uneven wear on your tire tread, you definitely need an alignment.",
        faqStillQuestions: "Still have questions?",
        faqContactUs: "Call during business hours to get your questions answered.",
        contactCTA: "Contact Us → (847) 844-1700",
        popupTitle: "Quick Question: When Was the Last Time You Had Your Wheels Aligned?",
        popupSubtitle: "Save your tires and your gas. Check availability in 30 seconds.",
        popupCTA: "Claim My $35 OFF Alignment (per axle) →",
        privacyPolicy: "Privacy Policy",
        termsOfUse: "Terms of Use",
        callUs: "Call Us:",
        slotsDone: "All appointment times for today have passed."
    },
    es: {
        readLess: "Leer menos",
        readMore: "Leer más",
        navClaimOffer: "Reclamar Oferta",
        heroClaimOffer: "¡Reclamar Oferta de Alineación Ahora!",
        bookNow: "Reservar ahora",
        limitedSlots: "Alineación de Ruedas Profesional",
        heroTitle: "<span class=\"text-transparent bg-clip-text bg-gradient-to-r from-cyan-400 to-blue-500\">Precisión Perfecta:</span> Obtenga $35 DE DESCUENTO en Alineación (por eje)",
        heroSubtitle: "Proteja sus neumáticos y mejore su consumo de combustible con una alineación de precisión. Asegúrese de que su vehículo ruede recto, se mantenga seguro y se maneje perfectamente. Reclame su cupón de $35 DE DESCUENTO hoy.",
        bulletAlignmentService: "Obtenga $35 DE DESCUENTO en Alineación Profesional (por eje)",
        bulletBonus1: "<strong>Bono 1:</strong> Inspección de Suspensión GRATIS (Valor de $59)",
        bulletBonus2: "<strong>Bono 2:</strong> Revisión y Ajuste de Presión de Neumáticos GRATIS",
        bulletBonus3: "<strong>Bono 3:</strong> Revisión de Componentes de Dirección GRATIS",
        bulletBonus4: "<strong>Bono 4:</strong> 15% DE DESCUENTO en Reparaciones de Suspensión Necesarias",
        heroCTA: "Reclamar mi $35 DE DESCUENTO en Alineación (por eje) →",
        trustedBy: "<span class=\"text-amber-400\">★★★★★</span> 4.9 de más de 250 conductores de Algonquin",
        scarcityLine: "⏰ Solo quedan 5 espacios de alineación esta semana",
        restrictionsApply: "Aplican restricciones.",
        seeDetails: "Ver detalles",
        disclaimerTitle: "Detalles de la oferta",
        disclaimerBody: "El especial de $35 DE DESCUENTO se aplica a la alineación de ruedas por eje para la mayoría de los automóviles de pasajeros y camionetas ligeras. El especial incluye ajustes de convergencia (toe). No se puede combinar con otras ofertas. Consulte en la tienda para obtener todos los detalles.",
        formTitle: "Asegura Tu Lugar - Comienza Aquí",
        formStep1: "Paso 1 de 2 — Sus datos de contacto.",
        formStep2: "Paso 2 de 2 — Elija su hora preferida.",
        formStep3: "", // Unused
        symptomSqueaking: "El vehículo se jala hacia un lado",
        symptomSpongy: "Desgaste desigual de los neumáticos",
        symptomShaking: "El volante está torcido",
        symptomLight: "El volante vibra",
        symptomCheck: "Solo necesito una revisión de rutina",
        nextBtn1: "Siguiente → Asegurar mi descuento",
        firstName: "Nombre",
        lastName: "Apellido",
        email: "Correo electrónico",
        mobileNumber: "Número de móvil",
        vehicleDetails: "Detalles del vehículo",
        carYear: "Año",
        carMake: "Marca",
        carModel: "Modelo",
        backBtn: "Atrás",
        nextBtn2: "Siguiente → Elegir una hora",
        availableTimes: "Horas disponibles",
        submitBtn: "Asegurar Mi Lugar →",
        noPaymentRequired: "No se requiere pago — esto solo reserva tu lugar.",
        requiredField: "Este campo es obligatorio",
        whenToReplaceTitle: "Cuándo alinear sus ruedas",
        whenToReplaceSubtitle: "Una mala alineación puede dañar sus neumáticos y comprometer su seguridad. Esté atento a estas señales de advertencia comunes.",
        watchSignsTitle: "Esté atento a estas señales",
        signSqueakingTitle: "El vehículo se jala hacia un lado",
        signSqueakingBody: "Si su auto se desvía a la izquierda o derecha cuando sujeta el volante recto, su alineación probablemente esté mal.",
        signSpongyTitle: "Desgaste desigual de neumáticos",
        signSpongyBody: "Revise su dibujo. Si un lado se desgasta más rápido que el otro, sus ruedas no están bien alineadas.",
        signStoppingTitle: "Vibración del volante",
        signStoppingBody: "Un volante que vibra puede ser señal de mala alineación o neumáticos desbalanceados.",
        signLightTitle: "Volante torcido",
        signLightBody: "Si su volante está descentrado mientras conduce recto, es hora de una alineación profesional.",
        dontWaitTitle: "No espere—Proteja sus neumáticos",
        dontWaitBody: "Retrasar una alineación corre el riesgo de arruinar un juego de neumáticos costosos en solo unas pocas miles de millas.",
        dontWaitCTA: "Reclamar $35 DE DESCUENTO en Alineación →",
        alignmentsPerformed: "Miles de alineaciones realizadas",
        expertRepairTitle: "Alineación de Ruedas de Precisión, Hecha con Cuidado.",
        expertRepairIntro: "En nuestro taller en Algonquin, utilizamos tecnología de alineación láser de última generación para asegurar que su vehículo cumpla con las especificaciones de fábrica. La alineación adecuada es clave para la longevidad de los neumáticos y la seguridad vial. Esto es lo que incluye nuestro proceso:",
        bulletEquipment: "Alineación Láser de Última Generación",
        bulletInspection: "Inspección de Suspensión Gratuita Incluida",
        bulletWarranty2: "<strong>Precisión Garantizada según las Especificaciones de Fábrica</strong>",
        bulletFinancing: "Financiamiento disponible a través de Snap",
        bulletVehicles: "Válido en la mayoría de los vehículos de pasajeros",
        trustedByDrivers: "Con la confianza de conductores en Algonquin, Lake in the Hills y más allá.",
        feature1Title: "Tecnología Láser de Punta",
        feature1Body: "Utilizamos sistemas láser Hunter Hawkeye de alta precisión para medir los ángulos de sus ruedas, asegurando un trayecto perfectamente recto.",
        feature2Title: "Revisión Integral de Suspensión",
        feature2Body: "Antes de alinear, inspeccionamos rótulas, terminales de dirección y bujes. No alineamos un auto con piezas gastadas que no mantendrán los ajustes.",
        feature3Title: "Informes Digitales Antes y Después",
        feature3Body: "La transparencia lo es todo. Recibirá un informe detallado que muestra la alineación de su vehículo antes y después de nuestros ajustes.",
        feature4Title: "Prueba de Manejo Experta",
        feature4Body: "Cada alineación es seguida por una prueba de manejo para confirmar que el volante esté perfectamente centrado y el vehículo se maneje exactamente como debería.",
        whyImportantTitle: "Por Qué No Debe Ignorar una Mala Alineación",
        whyImportantSubtitle: "La falta de alineación no es solo una molestia, es costosa e insegura.",
        pain1Title: "Destrucción Rápida de Neumáticos",
        pain1Body: "Las ruedas desalineadas pueden desgastar el dibujo de sus neumáticos en solo unas pocas miles de millas, costándole cientos en reemplazos prematuros.",
        pain2Title: "Pobre Economía de Combustible",
        pain2Body: "Cuando sus ruedas no apuntan hacia adelante, el motor trabaja más para empujar el auto, quemando más gasolina en cada milla.",
        pain3Title: "Manejo Inseguro",
        pain3Body: "La desalineación afecta su capacidad para maniobrar con precisión, especialmente en situaciones de emergencia o en carreteras mojadas.",
        reliefStatement: "🔒 Precisión Garantizada — Nos aseguramos de que su vehículo ruede recto, o lo corregiremos.",
        bookServiceCTA2: "Reclamar $35 DE DESCUENTO en Alineación →",
        trustRating: "4.9 Calificación de Google",
        trustRatingSub: "De más de 250 clientes satisfechos",
        trustExp: "Más de 10,000 alineaciones",
        trustExpSub: "Completado en Algonquin desde 2007",
        trustWarranty: "Precisión Garantizada",
        trustWarrantySub: "Tranquilidad garantizada",
        promiseTitle: "Nuestra Garantía de Alineación de Precisión",
        promiseSubtitle: "Cada alineación que realizamos está respaldada por nuestro compromiso con la precisión, la honestidad y su absoluta satisfacción.",
        promise1Title: "Precios Transparentes",
        promise1Body: "El precio que cotizamos es el que paga. Sin sorpresas, ni cargos ocultos. Solo trabajo honesto a un precio justo.",
        promise2Title: "Tecnología Moderna",
        promise2Body: "Utilizamos los últimos sistemas de alineación láser Hunter Hawkeye para una precisión y exactitud inigualables.",
        promise3Title: "Técnicos Expertos",
        promise3Body: "Nuestros técnicos experimentados son especialistas en alineación, asegurando que su servicio se realice bien a la primera.",
        promise4Title: "Garantía de Satisfacción",
        promise4Body: "Si no está satisfecho con cómo se maneja su auto después de nuestra alineación, tráigalo de vuelta y lo revisaremos gratis.",
        testimonialsTitle: "Con la confianza de los <span class=\"text-cyan-400\">conductores de Algonquin</span>",
        testimonialsSubtitle: "Los conductores de Algonquin confían en Queens Auto para alineaciones rápidas, asequibles y confiables. Vea por qué más de 25,000 clientes no van a otro lado.",
        loadMore: "Cargar más reseñas",
        aboutTitle: "El taller de confianza en Algonquin",
        aboutBody: "Queens Auto Service se enorgullece de servir a la comunidad de Algonquin con un cuidado automotriz confiable y honesto. Como taller familiar, tratamos a cada cliente como a un vecino. Ya sea para una alineación de precisión, neumáticos nuevos o mantenimiento de rutina, estamos aquí para ayudarle con precios justos.",
        aboutPoint1: "Precios honestos y transparentes",
        aboutPoint2: "Técnicos experimentados y profesionales",
        aboutPoint3: "Garantía de 24 meses / 24,000 millas en la mayoría de las reparaciones",
        aboutPoint4: "Más de 25,000 autos reparados y contando.",
        aboutSubtext: "Durante más de 17 años, hemos servido a Elgin, Carpntrsville, Dundee, Algonquin y las comunidades cercanas.",
        parallaxTitle: "¿Coche Jalando? ¡No Deje que Arruine sus Neumáticos!",
        parallaxBody: "La desalineación es la causa número uno del desgaste prematuro de los neumáticos. Ahorre $35 en su alineación (por eje) hoy y proteja sus neumáticos.",
        parallaxCTA: "Reclamar mi $35 DE DESCUENTO en Alineación (por eje) →",
        serviceAreaTitle: "Orgullosamente sirviendo a Algonquin y comunidades circundantes",
        faqTitle: "Preguntas frecuentes sobre alineación en Queens Auto",
        faqSubtitle: "Todo lo que necesita saber sobre nuestros servicios de alineación, respondido de forma clara y sencilla.",
        faq1q: "¿Con qué frecuencia debo alinear mi vehículo?",
        faq1a: "Recomendamos revisar la alineación cada 6,000 millas o cada vez que compre neumáticos nuevos. Si cae en un bache grande o nota que el coche jala, debe revisarlo de inmediato.",
        faq2q: "¿Cuánto tiempo toma una alineación?",
        faq2a: "La mayoría de las alineaciones en Queens Auto se completan en unos 45 a 60 minutos. Le entregaremos un informe detallado de los ajustes realizados.",
        faq3q: "¿Cuánto cuesta la alineación de ruedas?",
        faq3a: "Obtenga $35 DE DESCUENTO en nuestra alineación de precisión estándar por eje. Los precios varían según el vehículo, pero la mayoría ahorra significativamente con esta oferta.",
        faq4q: "¿Ofrecen garantía en el trabajo de alineación?",
        faq4a: "Garantizamos nuestro trabajo. Si nota algún problema con la dirección o manejo dentro de los 30 días posteriores al servicio, tráigalo para una revisión gratuita.",
        faq5q: "¿Puedo conducir con una mala alineación?",
        faq5a: "Technicamente sí, pero no es recomendable. Gastará los neumáticos mucho más rápido y el coche será más difícil de controlar. Es mucho más barato alinear que comprar neumáticos nuevos.",
        faq6q: "¿Qué vehículos alinean?",
        faq6a: "Trabajamos en la mayoría de los autos, SUVs y camionetas ligeras. Nuestro equipo es compatible con casi todas las marcas y modelos modernos.",
        faq7q: "¿Qué pasa si mi suspensión está gastada?",
        faq7a: "No hay problema. Realizamos una revisión gratuita de la suspensión antes de cada alineación. Si encontramos piezas gastadas, se lo informaremos primero.",
        faq8q: "¿La alineación incluye balanceo de neumáticos?",
        faq8a: "No, son servicios separados. La alineación ajusta los ángulos de las ruedas, mientras que el balanceo asegura que el peso sea uniforme. ¡Podemos hacer ambos si lo desea!",
        faq9q: "¿Cómo sé si necesito una alineación?",
        faq9a: "Si su volante está torcido, el auto jala hacia un lado o ve un desgaste desigual en sus neumáticos, definitivamente necesita una alineación.",
        faqStillQuestions: "¿Aún tiene preguntas?",
        faqContactUs: "Llámenos durante el horario de atención para resolver sus dudas.",
        contactCTA: "Contáctenos → (847) 844-1700",
        popupTitle: "¿Cuándo fue la última vez que alineó sus ruedas?",
        popupSubtitle: "Ahorre en neumáticos y gasolina. Verifique disponibilidad en 30 segundos.",
        popupCTA: "Reclamar mi $35 DE DESCUENTO en Alineación (por eje) →",
        privacyPolicy: "Política de privacidad",
        termsOfUse: "Términos de uso",
        callUs: "Llámenos:",
        slotsDone: "Todas las citas para hoy han pasado."
    }


};

export const allReviews: Review[] = [
    { "name": "Mark Devino", "text": "I got fast, friendly service here for a flat repair. Without any kind of appointment I got the tire fixed while I waited maybe 25 minutes. The repair was inexpensive. Great shop I will definitely be back." },
    { "name": "Bashar Danial", "text": "Gino and the Team, Wow!!! I recently had the misfortune of breaking down on the side of the road with a bad tire, called Queens Auto Service and spoke with Gino. They were very receptive and responsive, we got the vehicle to their shop, they immediately jumped into action and replaced the bad tire with a new tire and had us back on the road, all of this in under one hour!!! I highly recommend Queens Auto Service and Gino and the Team at this shop, top-notch!! Thank you for the help and great service." },
    { "name": "A C", "text": "HIGHLY RECOMMEND QUEENS TIRE IN ELGIN. Friendliness customer service. Prices are affordable, no extra unnecessary add ons. This will be my ONLY go to place. Much more than just tires" },
    { "name": "Nursultan Abeuov", "text": "Good place to get your tire, balancing, Alignment and more. Always good quality. Ill do all my pickup trucks alignment here, never regret it. Nick Abeuov🇰🇿" },
    { "name": "Kristin Kastern", "text": "Tires and axle shaft. They were amazing. I am new to the area and I am very happy 😊 with my service. They were honest and were able to fit me in on holiday weekend. The pricing was great. They even gave me really good advice about the car and tires. I am going to them in the future with all my cars. Thank you so much." },
    { "name": "Tim Chapman", "text": "Great customer service, went in for a second opinion for tire patch, nail in tire and advised not repairable too close to outer wall of tire. Good price and wound up buying all 4 new tires speedy service, Marco was a pleasure doing business with you. Would recommend this shop to anyone. These guys get it done and professional." },
    { "name": "Lavira Johnson", "text": "I called at the last minute to get in and have my battery replaced. I was given an exact quote, the part was in stock and I was encouraged to come in right away. When I arrived, I was greeted and checked in immediately in a very kind and professional manner by Baltazar. I was quoted 30-45 mins and it didn't feel like more than 25 and I came in about an hour before closing time. Fast and exceptional service, reasonably priced.. Will definitely patronize this business again. Pep Boys, only 5 minutes away wanted almost $300 more for the same service and wanted to-keep my car overnight." },
    { "name": "Theresa Hoge", "text": "Highly recommend! Probably one of the best shops I’ve been too. Service is professional and super nice. I had to get my brakes done. They got me in the same day, were done in a few hours and explained everything to me. I also needed to get new tires and they walked me through all the options. I recently ran over a nail and they were able to patch the hole right away. Quality of work is great and the customer service is everything! Really appreciate them!" }
];

export const allReviewsEs: Review[] = [
    { "name": "Mark Devino", "text": "Recibí un servicio rápido y amigable aquí para una reparación de pinchazo. Sin ningún tipo de cita, me arreglaron el neumático mientras esperaba unos 25 minutos. La reparación no fue cara. Gran taller, definitivamente volveré." },
    { "name": "Bashar Danial", "text": "¡Gino y el equipo, guau! Recientemente tuve la mala suerte de quedarme tirado en la carretera con un neumático en mal estado, llamé a Queens Auto Service y hablé con Gino. Fueron muy receptivos y respondieron rápidamente, llevamos el vehículo a su taller, inmediatamente se pusieron en acción y reemplazaron el neumático dañado por uno nuevo y nos pusieron de nuevo en la carretera, ¡todo esto en menos de una hora! Recomiendo encarecidamente Queens Auto Service y a Gino y el equipo de este taller, ¡de primera categoría! Gracias por la ayuda y el gran servicio." },
    { "name": "A C", "text": "RECOMIENDO ENCARECIDAMENTE QUEENS TIRE EN ELGIN. Amabilidad en el servicio al cliente. Los precios son asequibles, sin extras innecesarios. Este será mi ÚNICO lugar de referencia. Mucho más que solo neumáticos." },
    { "name": "Nursultan Abeuov", "text": "Buen lugar para comprar neumáticos, balanceo, alineación y más. Siempre de buena calidad. Haré la alineación de todas mis camionetas aquí, nunca me arrepiento. Nick Abeuov🇰🇿" },
    { "name": "Kristin Kastern", "text": "Neumáticos y eje. Fueron increíbles. Soy nueva en la zona y estoy muy contenta 😊 con mi servicio. Fueron honestos y pudieron atenderme en un fin de semana festivo. El precio fue excelente. Incluso me dieron muy buenos consejos sobre el coche y los neumáticos. En el futuro, iré a ellos con todos mis coches. Muchas gracias." },
    { "name": "Tim Chapman", "text": "Excelente servicio al cliente, fui para una segunda opinión sobre un parche de neumático, un clavo en el neumático y me informaron que no era reparable por estar demasiado cerca de la pared exterior del neumático. Buen precio y terminé comprando los 4 neumáticos nuevos, servicio rápido. Marco, fue un placer hacer negocios contigo. Recomendaría este taller a cualquiera. Estos chicos hacen el trabajo y son profesionales." },
    { "name": "Lavira Johnson", "text": "Llamé en el último momento para que me reemplazaran la batería. Me dieron un presupuesto exacto, la pieza estaba en stock y me animaron a ir de inmediato. Cuando llegué, me saludaron y me registraron de inmediato de una manera muy amable y profesional por Baltazar. Me dijeron que tardarían entre 30 y 45 minutos y no parecieron más de 25, y llegué aproximadamente una hora antes de la hora de cierre. Servicio rápido y excepcional, a un precio razonable. Definitivamente volveré a este negocio. Pep Boys, a solo 5 minutos de distancia, quería casi $300 más por el mismo servicio y querían quedarse con mi coche durante la noche." },
    { "name": "Theresa Hoge", "text": "¡Lo recomiendo encarecidamente! Probablemente uno de los mejores talleres en los que he estado. El servicio es profesional y súper agradable. Tuve que hacer mis frenos. Me atendieron el mismo día, terminaron en unas pocas horas y me explicaron todo. También necesitaba neumáticos nuevos y me guiaron a través de todas las opciones. Recientemente pisé un clavo y pudieron parchar el agujero de inmediato. ¡La calidad del trabajo es excelente y el servicio al cliente lo es todo! ¡Realmente los aprecio!" }
];
